### ISSUE TITLE
Guice does not work with Lambdas

### ISSUE THREAD

**Issue by mthiele** [sialcasa/mvvmFX#177]
When using the Cdi-Guice module and using lambdas in the method of the viewmodel that has the `@Inject` annotation, the initialization of the viewmodel crashes. An `IndexOutOfBoundsException` is thrown by the ASM framework (version 3) that Guice internally uses.
ASM does support Java 8 since version 5.x.

Exception:
`
com.google.inject.internal.util.$ComputationException: java.lang.ArrayIndexOutOfBoundsException: 3434
    at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:553)
    at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:419)
    at   com.google.inject.internal.util.$CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2041)
    at com.google.inject.internal.util.$StackTraceElements.forMember(StackTraceElements.java:53)
    at com.google.inject.internal.Errors.formatSource(Errors.java:690)
    at com.google.inject.internal.Errors.formatInjectionPoint(Errors.java:720)
    at com.google.inject.internal.Errors.formatSource(Errors.java:684)
    at com.google.inject.internal.Errors.format(Errors.java:555)
    at com.google.inject.ProvisionException.getMessage(ProvisionException.java:59)
    ...
Caused by: java.lang.ArrayIndexOutOfBoundsException: 3434
    at com.google.inject.internal.asm.$ClassReader.readClass(Unknown Source)
    at com.google.inject.internal.asm.$ClassReader.accept(Unknown Source)
    at com.google.inject.internal.asm.$ClassReader.accept(Unknown Source)
    at com.google.inject.internal.util.$LineNumbers.<init>(LineNumbers.java:62)
    at com.google.inject.internal.util.$StackTraceElements$1.apply(StackTraceElements.java:36)
    at com.google.inject.internal.util.$StackTraceElements$1.apply(StackTraceElements.java:33)
    at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:549)
    ... 38 more
`

**Comment by manuel-mauky** [comment]
I extended the existing guice integration test. Now a dummy Service interface with an implementation is used and a guice module that binds the implementation to the interface. 
The service is injected into the viewModel. Both in the guice module and in the viewModel now Lambdas are used. 
With this setup I couln't reproduce your bug. 

Maybe there is another problem with your application setup. If you still think that there is a bug with our Guice module it would help if you could provide some example code or even a test case that reproduces the bug. In this case I will open this issue again.
