### ISSUE TITLE
FXML views can't be loaded when using Jandex with mvvmfx-cdi / Weld-SE

### ISSUE THREAD

**Issue by ssaring** [sialcasa/mvvmFX#242]
I'm using mvvmfx-cdi 1.2.1 with weld-se 2.2.11.Final as the CDI implementation. The environment is Java 1.8.0_45 64 bit on Windows 8.1.

When starting the application and so the CDI container a warning is shown that the Jandex library should be used to improve the CDI startup and lookup performance. So I've added the Jandex library to the classpath via:

```
    <dependency>
        <groupId>org.jboss</groupId>
        <artifactId>jandex</artifactId>
        <version>1.2.4.Final</version>
    </dependency>
```

The Jandex library is being used then, the warning is not shown anymore. But the application fails to start, because the FXML view can't be loaded anymore. 
Here's the exception:

```
Mai 15, 2015 9:17:17 AM org.jboss.weld.bootstrap.WeldStartup <clinit>
INFO: WELD-000900: 2.2.11 (Final)
Mai 15, 2015 9:17:17 AM org.jboss.weld.environment.deployment.discovery.DiscoveryStrategyFactory create
INFO: WELD-ENV-000020: Using jandex for bean discovery
Mai 15, 2015 9:17:17 AM org.jboss.weld.bootstrap.WeldStartup startContainer
INFO: WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
Mai 15, 2015 9:17:18 AM org.jboss.weld.interceptor.util.InterceptionTypeRegistry <clinit>
WARN: WELD-001700: Interceptor annotation class javax.ejb.PostActivate not found, interception based on it is not enabled
Mai 15, 2015 9:17:18 AM org.jboss.weld.interceptor.util.InterceptionTypeRegistry <clinit>
WARN: WELD-001700: Interceptor annotation class javax.ejb.PrePassivate not found, interception based on it is not enabled
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
    at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$152(LauncherImpl.java:182)
    at com.sun.javafx.application.LauncherImpl$$Lambda$2/935044096.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: javafx.fxml.LoadException: 
/D:/Projects/.../target/classes/.../FooView.fxml:8

    at de.saxsys.mvvmfx.internal.viewloader.FxmlViewLoader.loadFxmlViewTuple(FxmlViewLoader.java:149)
    at de.saxsys.mvvmfx.internal.viewloader.FxmlViewLoader.loadFxmlViewTuple(FxmlViewLoader.java:67)
    at de.saxsys.mvvmfx.FluentViewLoader$FxmlViewStep.load(FluentViewLoader.java:184)
    at de.....FooApplication.setupApplicationWindow(FooApplication.java:32)
    at de....FooApplication.startMvvmfx(FooApplication.java:25)
    at de.saxsys.mvvmfx.cdi.MvvmfxCdiApplication.start(MvvmfxCdiApplication.java:72)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$159(LauncherImpl.java:863)
    at com.sun.javafx.application.LauncherImpl$$Lambda$54/1381399698.run(Unknown Source)
    at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$172(PlatformImpl.java:326)
    at com.sun.javafx.application.PlatformImpl$$Lambda$48/2084172243.run(Unknown Source)
    at com.sun.javafx.application.PlatformImpl.lambda$null$170(PlatformImpl.java:295)
    at com.sun.javafx.application.PlatformImpl$$Lambda$50/1145673344.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(PlatformImpl.java:294)
    at com.sun.javafx.application.PlatformImpl$$Lambda$49/535984314.run(Unknown Source)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$null$145(WinApplication.java:101)
    at com.sun.glass.ui.win.WinApplication$$Lambda$38/423056972.run(Unknown Source)
    ... 1 more
Caused by: javafx.fxml.LoadException: 
/D:/Projects/.../classes/de/.../FooView.fxml:8

    at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2605)
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2583)
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2445)
    at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2413)
    at de.saxsys.mvvmfx.internal.viewloader.FxmlViewLoader.loadFxmlViewTuple(FxmlViewLoader.java:129)
    ... 19 more
Caused by: org.jboss.weld.exceptions.UnsatisfiedResolutionException: WELD-001308: Unable to resolve any beans for Type: class de....FooView; Qualifiers: [@javax.enterprise.inject.Any()]
    at org.jboss.weld.bean.builtin.InstanceImpl.get(InstanceImpl.java:101)
    at de.saxsys.mvvmfx.cdi.MvvmfxCdiApplication.lambda$new$0(MvvmfxCdiApplication.java:54)
    at de.saxsys.mvvmfx.cdi.MvvmfxCdiApplication$$Lambda$51/1674320272.call(Unknown Source)
    at de.saxsys.mvvmfx.internal.viewloader.DependencyInjector.getInstanceOf(DependencyInjector.java:70)
    at de.saxsys.mvvmfx.internal.viewloader.FxmlViewLoader$DefaultControllerFactory.call(FxmlViewLoader.java:206)
    at de.saxsys.mvvmfx.internal.viewloader.FxmlViewLoader$DefaultControllerFactory.call(FxmlViewLoader.java:197)
    at javafx.fxml.FXMLLoader$ValueElement.processAttribute(FXMLLoader.java:925)
    at javafx.fxml.FXMLLoader$InstanceDeclarationElement.processAttribute(FXMLLoader.java:967)
    at javafx.fxml.FXMLLoader$Element.processStartElement(FXMLLoader.java:216)
    at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:740)
    at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2711)
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2531)
    ... 22 more
```

**Comment by manuel-mauky** [comment]
When adding the jandex dependency to the [contacts example app](https://github.com/sialcasa/mvvmFX/tree/develop/examples/mvvmfx-contacts) it works without problems. 
During the startup I get the following message:
`15:10:20.139 [JavaFX Application Thread] INFO  org.jboss.weld.Bootstrap - WELD-ENV-000020: Using jandex for bean discovery`

But I will further investigate this issue now.

**Comment by manuel-mauky** [comment]
When I set `bean-discovery-mode` to `annotated` and added Jandex to the example app, I got errors for unsatisfied dependencies. To fix this I've replaced `@Singleton` with `@ApplicationScoped` (which isn't the same but sufficient in my case) and added `@Dependent` to all View and ViewModel classes in the example app. 

With this setup the contacts example app is running just fine without any exceptions. I assume that there is some misconfiguration in your setup. Make sure that all beans are properly annotated.

If you can provide a (small) example or more informations I will further investigate your issue. Otherwise I will close this issue for now. But feel free to open it again if the problem still exists.

I will not commit the discribed changes to the contacts example app as it makes the example more complex.
