### ISSUE TITLE
unreliable test in CompositeCommandTest

### ISSUE THREAD

**Issue by manuel-mauky** [sialcasa/mvvmFX#260]
The tests in `CompositeCommandTest` are unreliable. While the code works in rare situations the tests are failing due to `java.util.concurrent.TimeoutException`s.

This needs to be fixed to get a stable and reliable build.

**Comment by manuel-mauky** [comment]
```
longRunningAsyncComposite(de.saxsys.mvvmfx.utils.commands.CompositeCommandTest)  Time elapsed: 5.264 sec  <<< ERROR!
java.util.concurrent.TimeoutException
    at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1763)
    at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1907)
    at de.saxsys.mvvmfx.utils.commands.CompositeCommandTest.longRunningAsyncComposite(CompositeCommandTest.java:242)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at com.cedarsoft.test.utils.CatchAllExceptionsRule$1.evaluate(CatchAllExceptionsRule.java:31)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at de.saxsys.javafx.test.JfxRunner.access$001(JfxRunner.java:18)
    at de.saxsys.javafx.test.JfxRunner.runChild(JfxRunner.java:51)
    at de.saxsys.javafx.test.JfxRunner.runChild(JfxRunner.java:18)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
    at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

**Comment by manuel-mauky** [comment]
https://travis-ci.org/sialcasa/mvvmFX/builds/66392107

**Comment by manuel-mauky** [comment]
I have set the timeouts higher in the failing test. We will watch this issue to see if the test still breaks. I will let this issue open until more time has passed without failing builds.

**Comment by manuel-mauky** [comment]
https://travis-ci.org/sialcasa/mvvmFX/builds/69106876

**Comment by manuel-mauky** [comment]
The test is still fails from time to time. For this reason I've marked the test case with `@Ignore`. This test case really needs to be fixed.
