### ISSUE TITLE
mvvmfx-validation 1.7.0 missing controlsfx dependency

### ISSUE THREAD

**Issue by No3x** [sialcasa/mvvmFX#525]
I upgraded mvvmFX from 1.6.0 to 1.7.0. Since then the Validation doesn't work
`new ControlsFxVisualizer();` results in

```
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.GeneratedMethodAccessor31.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2566)
	... 53 more
Caused by: java.lang.NoClassDefFoundError: org/controlsfx/validation/decoration/GraphicValidationDecoration
	at de.saxsys.mvvmfx.utils.validation.visualization.ControlsFxVisualizer.<init>(ControlsFxVisualizer.java:41)
	at org.recipes2pdf.gui.cookbook.AddCookbookView.initialize(AddCookbookView.java:56)
	... 63 more
Caused by: java.lang.ClassNotFoundException: org.controlsfx.validation.decoration.GraphicValidationDecoration
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 65 more
```
1.6.0 vs. 1.7.0 dependencies
![s](https://user-images.githubusercontent.com/2690708/31035076-f17d4c04-a566-11e7-9fd5-32ca01a090f3.PNG)
![t](https://user-images.githubusercontent.com/2690708/31035075-f163e372-a566-11e7-9bc8-e69bb5ceea36.PNG)

So controlsfx dependency is missing in 1.7.0. Adding it manually to the project dependencies is a workaround.

**Comment by manuel-mauky** [comment]
It's intentionally that the dependency is not defined. It was by mistake that version 1.6.0 had the dependency defined. See #482 for the issue that this change was made for.

Before version 1.6.0 the validation classes were part of the mvvmfx core module and the dependency to controlsfx was set to "provided" which means that you had to add the dependency by yourself. This is also documented in our [wiki](https://github.com/sialcasa/mvvmFX/wiki/Validation#controlsfxvisualizer). 

However, with version 1.6.0 we moved the validation classes to their own module mvvmfx-validation. With this transition the "provided" tag was lost by mistake and therefore version 1.6.0 had an explicit dependency to controlsfx. 
With version 1.7.0 we removed this dependency again to fix this.

The reason is that this way it's easier for you as a user to change the version of controlsfx without depending on us. You can switch to a newer controlsfx version without having to update mvvmfx-validation (at least as long as they don't make breaking changes like removing classes that we depend on).

**Comment by No3x** [comment]
Oh, I thought it was by mistake! I checked the first paragraphs of this wiki only for any hint on this dependency. It's not a big deal anyway.
